version: '3.8'

volumes:
  nccrd_next:
    driver: local

networks:
  nccrd_next:
    name: nccrd_next
    driver: overlay
    attachable: true    

services:
  nccrd:
    image: $NCCRD_IMAGE
    deploy:
      replicas: 1
      restart_policy:
        condition: 'any'
        delay: 5s
        max_attempts: 3
        window: 120s   
    volumes:
      - nccrd_next:/nccrd-assets
    environment:
        FILES_DIRECTORY: $FILES_DIRECTORY
        LOG_REQUEST_DETAILS: $LOG_REQUEST_DETAILS
        LOG_SQL_QUERIES: false
        MSSQL_DATABASE: nccrd_next
        MSSQL_HOSTNAME: $MSSQL_HOSTNAME
        MSSQL_PASSWORD: $MSSQL_PASSWORD
        MSSQL_PORT: 2433
        MSSQL_USERNAME: $MSSQL_USERNAME
        NCCRD_API_ALLOWED_ORIGINS: $NCCRD_API_ALLOWED_ORIGINS
        NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES: $NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES
        NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES: $NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES
        NCCRD_DEPLOYMENT_ENV: $NCCRD_DEPLOYMENT_ENV
        NCCRD_HOSTNAME: $NCCRD_HOSTNAME
        NCCRD_SSL_ENV: $NCCRD_SSL_ENV
        SAEON_AUTH_CLIENT_SECRET: $SAEON_AUTH_CLIENT_SECRET
    ports:
      - 9000:3000
    networks:
      - nccrd_next