version: '3.8'

volumes:
  nccrd_next:
    driver: local

networks:
  nccrd_next:
    name: nccrd_next
    driver: overlay
    attachable: true    

services:
  nginx:
    image: $NGINX_IMAGE
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 9000:80
    networks:
      - nccrd_next

  nccrd:
    image: $NCCRD_IMAGE
    deploy:
      replicas: 1
      restart_policy:
        condition: 'any'
        delay: 5s
        max_attempts: 3
        window: 120s   
    volumes:
      - nccrd_next:/nccrd-assets
    environment:
      FILES_DIRECTORY: /nccrd-assets
      LOG_REQUEST_DETAILS: 'false'
      LOG_SQL_QUERIES: 'false'
      MSSQL_DATABASE: nccrd_next
      MSSQL_HOSTNAME: mssql.saeon.int
      MSSQL_PASSWORD: $MSSQL_PASSWORD
      MSSQL_PORT: 3433
      MSSQL_USERNAME: $MSSQL_USERNAME
      NCCRD_API_ALLOWED_ORIGINS: https://nccrd.saeon.ac.za
      NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES: ''
      NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES: zd.smith@saeon.nrf.ac.za
      NCCRD_DEPLOYMENT_ENV: production
      NCCRD_HOSTNAME: https://nccrd.saeon.ac.za
      NCCRD_SSL_ENV: production
      SAEON_AUTH_CLIENT_SECRET: $SAEON_AUTH_CLIENT_SECRET
    networks:
      - nccrd_next