version: '3.8'

networks:
  nccs_default:
    name: $NCCRD_DOCKER_NETWORK

volumes:
  sql-server:
    driver: local

services:
  sql-server-express:
    container_name: sql-server-express
    restart: always
    image: $MSSQL_IMAGE
    volumes: 
      - sql-server:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: $MSSQL_SA_PASSWORD
      MSSQL_PID: $MSSQL_PID
    ports:
      - 1433:1433
    networks:
      - $NCCRD_DOCKER_NETWORK

  nccrd:
    container_name: nccrd
    volumes:
      - /opt/nccrd-assets:/nccrd-assets
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOG_REQUEST_DETAILS: $LOG_REQUEST_DETAILS
        FILES_DIRECTORY: $FILES_DIRECTORY
        LOG_SQL_QUERIES: $LOG_SQL_QUERIES
        NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES: $NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES
        NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES: $NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES
        NCCRD_API_RESET_SCHEMA: $NCCRD_API_RESET_SCHEMA
        SAEON_AUTH_CLIENT_ID: $SAEON_AUTH_CLIENT_ID
        SAEON_AUTH_CLIENT_SCOPES: $SAEON_AUTH_CLIENT_SCOPES
        SAEON_AUTH_CLIENT_SECRET: $SAEON_AUTH_CLIENT_SECRET
        NCCRD_HOSTNAME: $NCCRD_HOSTNAME
        NCCRD_DEPLOYMENT_ENV: $NCCRD_DEPLOYMENT_ENV
        NCCRD_SSL_ENV: $NCCRD_SSL_ENV
        MSSQL_USERNAME: $MSSQL_USERNAME
        MSSQL_PASSWORD: $MSSQL_PASSWORD
        MSSQL_HOSTNAME: $MSSQL_HOSTNAME
        MSSQL_DATABASE: $MSSQL_DATABASE
        MSSQL_PORT: $MSSQL_PORT
    ports:
      - 3000:3000
    depends_on: 
      - sql-server-express
    networks: 
      - $NCCRD_DOCKER_NETWORK
