version: '3.8'

volumes:
  nccrd_stable:
    driver: local

networks:
  nccrd_stable:
    name: nccrd_stable
    driver: overlay
    attachable: true    

services:
  nccrd:
    image: $NCCRD_IMAGE
    deploy:
      replicas: 1
      restart_policy:
        condition: 'any'
        delay: 5s
        max_attempts: 3
        window: 120s   
    volumes:
      - nccrd_stable:/nccrd-assets
    environment:
        NCCRD_API_ALLOWED_ORIGINS: $NCCRD_API_ALLOWED_ORIGINS
        LOG_REQUEST_DETAILS: $LOG_REQUEST_DETAILS
        FILES_DIRECTORY: $FILES_DIRECTORY
        LOG_SQL_QUERIES: $LOG_SQL_QUERIES
        NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES: $NCCRD_DEFAULT_SYSADMIN_EMAIL_ADDRESSES
        NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES: $NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES
        SAEON_AUTH_CLIENT_ID: $SAEON_AUTH_CLIENT_ID
        SAEON_AUTH_CLIENT_SCOPES: $SAEON_AUTH_CLIENT_SCOPES
        SAEON_AUTH_CLIENT_SECRET: $SAEON_AUTH_CLIENT_SECRET
        NCCRD_HOSTNAME: $NCCRD_HOSTNAME
        NCCRD_DEPLOYMENT_ENV: $NCCRD_DEPLOYMENT_ENV
        NCCRD_SSL_ENV: $NCCRD_SSL_ENV
        MSSQL_USERNAME: $MSSQL_USERNAME
        MSSQL_PASSWORD: $MSSQL_PASSWORD
        MSSQL_HOSTNAME: $MSSQL_HOSTNAME
        MSSQL_DATABASE: $MSSQL_DATABASE
        MSSQL_PORT: $MSSQL_PORT
    ports:
      - 9000:3000
    networks:
      - nccrd_stable