name: deployment@stable

on:
  push:
    branches:
      - stable

jobs:

  source-code:
    runs-on: github-runner.saeon.int
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable

  build-image:
    runs-on: github-runner.saeon.int
    steps:
      - name: Build Docker image
        run: >
          docker image build -t nccrd -f Dockerfile .
          --build-arg SAEON_AUTH_CLIENT_SECRET="${{ secrets.SAEON_AUTH_CLIENT_SECRET}}"
          --build-arg NCCRD_HOSTNAME="https://nccrd.environment.gov.za"

  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - name: Deploy image
        run: |
          echo hi there