name: deployment@stable

on:
  push:
    branches:
      - stable

jobs:

  source-code:
    runs-on: nccrd.environment.gov.za
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable  

  deploy:
    needs: [source-code]
    runs-on: nccrd.environment.gov.za
    steps:
      - name: Deploy services
        run: >-
          SAEON_AUTH_CLIENT_SECRET="${{ secrets.SAEON_AUTH_CLIENT_SECRET}}"
          NCCRD_HOSTNAME="https://nccrd.environment.gov.za"
          MSSQL_SA_PASSWORD="${{ secrets.MSSQL_PASSWORD}}"
          MSSQL_USERNAME="${{ secrets.MSSQL_USERNAME}}"
          MSSQL_PASSWORD="${{ secrets.MSSQL_PASSWORD}}"        
          MSSQL_PID="Express"
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build