name: deployment@stable

on:
  push:
    tags:
      - '*'
    branches:
      - stable

jobs:

  source-code:
    runs-on: nccrd.saeon.ac.za
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable

  pkg-releases:
    needs: [source-code]
    runs-on: nccrd.saeon.ac.za
    
    steps:
      - name: Build binaries via Docker
        run: |
          docker image build -t nccrd-binaries -f pkg.Dockerfile .

      - name: Get binaries from Docker context
        run: |
          docker cp $(docker create --rm nccrd-binaries):/app/binaries/ ./
      
      - name: Publish binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/nccrd-linux
            binaries/nccrd-macos
            binaries/nccrd-win.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_NCCRD_RELEASES }}

      - name: Clean up
        run: |
          docker image rm nccrd-binaries
          rm -rf binaries
