name: deployment@stable

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: nccrd.saeon.ac.za
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable

      - name: Deploy services
        run: >-
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build