name: deployment@stable

on:
  push:
    branches:
      - stable

jobs:
  deploy:
    runs-on: nccrd.saeon.ac.za
    steps:
      - uses: actions/checkout@v2
        with:
          ref: stable

      - name: Deploy services
        run: >-
          SAEON_AUTH_CLIENT_SECRET="${{ secrets.SAEON_AUTH_CLIENT_SECRET}}"
          SAEON_AUTH_OAUTH_REDIRECT_ADDRESS="https://nccrd.saeon.ac.za/http/authenticate/redirect/saeon"
          NCCRD_DEFAULT_ADMIN_EMAIL_ADDRESSES="zach@saeon.ac.za"
          /usr/local/bin/docker-compose --env-file docker-compose.env up -d --force-recreate --build